server:
  port: 9001
  servlet:
    context-path: /v1/auth

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  data:
    mongodb:
      auth:
        uri: ${AUTH_URI}
      resource:
        uri: ${RESOURCE_URI}

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true