server:
  port: 9001

logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  data:
    mongodb:
      auth:
        uri: mongodb://localhost:27017/AUTHORIZATION
      resource:
        uri: mongodb://localhost:27017/RESOURCE

  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "tcc.uff.email@gmail.com"
    password: "zfedcsqnvmxfbiob"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true